### ISSUE TITLE
Error code

### ISSUE THREAD

**Issue by PaulRoorda** [lvanderree/com.synplyworks.casambi#5]
d2e97949-bf27-4323-9eb8-e4eee9faac2e

Casambi app toegevoegd aan Homey Pro. Alle lampen worden herkend en opgeslagen. Helaas is geen van de lampen e bedienen.

**Comment by lvanderree** [comment]
Ik vermoed dat de telefoon met de casambi gateway software niet gevonden
kan worden. Homey kan helaas niet zelf met de lampen praten, de casambi app
moet op de telefoon draaien.
--

Met vriendelijke groet
Leon van der Ree


Op vr 10 nov 2023 om 15:12 schreef PaulRoorda ***@***.***>:

**Comment by PaulRoorda** [comment]
Beste Leon,

Het werkt! Top! Mijn telefoon met casambi gateway was offline!

Met vriendelijke groet,

Paul Roorda




Op vr 10 nov 2023 om 16:44 schreef Leon van der Ree <
***@***.***>:
