### ISSUE TITLE
Casambi network cannot be controlled from Homey Pro

### ISSUE THREAD

**Issue by jensburgers** [lvanderree/com.synplyworks.casambi#6]
Dear Leon, your app has worked well until now. For some reason Homey cannot control any Casambi
Device anymore. The controller (an iPad) is logged in. I have deleted the app from my Homey Pro and reinstalled it, logged in and was able to find all devices. Hope you can help.

**Comment by RolandWeiss** [comment]
Dear Leon, 
I would like to buy the CASAMBI Cloud Gateway or the CASAMBI GWLBT2N CBU Gateway. 
Do both work in your app?

[808941.pdf](https://github.com/lvanderree/com.synplyworks.casambi/files/14311280/808941.pdf)
[Casambi Gateway Datasheet v 2.0.pdf](https://github.com/lvanderree/com.synplyworks.casambi/files/14311317/Casambi.Gateway.Datasheet.v.2.0.pdf)
